FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY gui ./gui

WORKDIR /app/gui

EXPOSE 8080

CMD streamlit run UI.py \
    --server.port=${PORT:-8080} \
    --server.address=0.0.0.0
