from typing import List, Dict, Optional

def _escape(text: str) -> str:
    """Escape LaTeX special chars for dynamic content (not for raw LaTeX blocks)."""
    if not isinstance(text, str):
        text = str(text)

    replacements = {
        "\\": r"\\",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text


def build_ieee_latex_report(
    topic: str,
    summaries: List[Dict],
    gaps: List[str],
    citations: List[Dict],
    experiment_plan: Dict,
    author_block: Optional[str] = None,
) -> str:
    """
    Build a full IEEE-conference style LaTeX document (IEEEtran).
    Optimized for Overleaf/PDF use.
    """

    # default dummy author block if user doesn't supply
    if not author_block:
        author_block = (
            r"Author One, Author Two% <-this % stops a space \\" "\n"
            r"Department of Aerospace Engineering \\" "\n"
            r"Institute of Advanced Research \\" "\n"
            r"City, Country \\" "\n"
            r"{\tt\small author1@example.com, author2@example.com} \\ \\" "\n"
            r"Advisor: Dr. Advisor Name \\" "\n"
            r"Department of Aerospace Engineering \\" "\n"
            r"Institute of Advanced Research \\" "\n"
            r"City, Country \\" "\n"
            r"{\tt\small advisor@example.com}"
        )

    tex: List[str] = []

    # ------------------------------------------------------------------
    # Preamble and class  (SWITCHED TO IEEEtran)
    # ------------------------------------------------------------------
    tex.append(r"\documentclass[conference]{IEEEtran}")
    tex.append(r"\IEEEoverridecommandlockouts")  # ok for IEEEtran
    tex.append("")
    tex.append(r"% Packages")
    tex.append(r"\usepackage{graphics}")
    tex.append(r"\usepackage{epsfig}")
    tex.append(r"\usepackage{amsmath}")
    tex.append(r"\usepackage{amssymb}")
    tex.append(r"\usepackage{url}")
    tex.append(r"\usepackage[ruled, vlined, linesnumbered]{algorithm2e}")
    tex.append(r"\usepackage{verbatim}")
    tex.append(r"\usepackage{soul, color}")
    tex.append(r"\usepackage{lmodern}")
    tex.append(r"\usepackage{fancyhdr}")
    tex.append(r"\usepackage[utf8]{inputenc}")
    tex.append(r"\usepackage{fourier}")
    tex.append(r"\usepackage{array}")
    tex.append(r"\usepackage{makecell}")
    tex.append(r"\usepackage{graphicx}")
    tex.append(r"\usepackage{hyperref}")
    tex.append("")
    tex.append(r"\SetNlSty{large}{}{:}")
    tex.append(r"\renewcommand\theadalign{bc}")
    tex.append(r"\renewcommand\theadfont{\bfseries}")
    tex.append(r"\renewcommand\theadgape{\Gape[4pt]}")
    tex.append(r"\renewcommand\cellgape{\Gape[4pt]}")
    tex.append("")

    # ------------------------------------------------------------------
    # Title & author  (IEEEtran style)
    # ------------------------------------------------------------------
    tex.append(r"\title{" + _escape(topic) + r"}")
    tex.append("")
    tex.append(r"\author{" + author_block + r"}")
    tex.append("")
    tex.append(r"\begin{document}")
    tex.append("")
    tex.append(r"\maketitle")
    tex.append("")

    # ------------------------------------------------------------------
    # Abstract
    # ------------------------------------------------------------------
    tex.append(r"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    tex.append(r"\begin{abstract}")
    abstract_text = (
        "This research paper is automatically generated by an AI-based multi-agent system. "
        "It analyzes existing literature on Thermal Protection Systems (TPS), identifies "
        "research gaps, and proposes a structured experimental design to evaluate new TPS "
        "materials and architectures for crew module re-entry."
    )
    tex.append(_escape(abstract_text) + r"\\")
    tex.append(r"\end{abstract}")
    tex.append("")

    # ------------------------------------------------------------------
    # Keywords (IEEEtran: IEEEkeywords)
    # ------------------------------------------------------------------
    tex.append(r"\begin{IEEEkeywords}")
    tex.append(_escape("Thermal Protection System, TPS, Re-entry, Materials, Simulation, Hybrid TPS"))
    tex.append(r"\end{IEEEkeywords}")
    tex.append("")
    tex.append(r"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")

    # ------------------------------------------------------------------
    # INTRODUCTION
    # ------------------------------------------------------------------
    tex.append(r"\section{INTRODUCTION}")
    intro_text = (
        "Thermal Protection Systems (TPS) are critical for protecting crew modules during high-enthalpy "
        "atmospheric re-entry. This section provides an overview of the problem domain and summarizes "
        "the key prior works analyzed by the AI Summarizer Agent."
    )
    tex.append(_escape(intro_text) + r"\par")
    tex.append("")

    # brief per-paper mini summary
    for p in summaries:
        title = _escape(p.get("title", "Unnamed Paper"))
        tex.append(r"\subsection{" + title + r"}")
        tex.append(_escape(p.get("summary", "No summary provided.")) + r"\par")
        tex.append("")

    # ------------------------------------------------------------------
    # LITERATURE SURVEY
    # ------------------------------------------------------------------
    tex.append(r"\section{LITERATURE SURVEY}")
    if not summaries:
        tex.append(
            _escape(
                "No structured literature entries were available at generation time. "
                "This section will be populated when more data is provided to the Summarizer Agent."
            )
        )
        tex.append("")
    else:
        tex.append(
            _escape(
                "This section synthesizes methods, key findings, and limitations from the analyzed papers."
            )
            + r"\par"
        )
        tex.append("")
        for p in summaries:
            title = _escape(p.get("title", ""))
            tex.append(r"\subsection{" + title + r"}")
            methods = ", ".join(p.get("methods", []))
            findings = ", ".join(p.get("key_findings", []))
            limits = ", ".join(p.get("limitations", []))
            tex.append(r"\textbf{Methods:} " + _escape(methods) + r"\par")
            tex.append(r"\textbf{Key Findings:} " + _escape(findings) + r"\par")
            tex.append(r"\textbf{Limitations:} " + _escape(limits) + r"\par")
            tex.append("")

    # ------------------------------------------------------------------
    # RESEARCH GAPS
    # ------------------------------------------------------------------
    tex.append(r"\section{RESEARCH GAPS}")
    tex.append(
        _escape(
            "Based on the literature survey, the following open research gaps are identified by the AI system:"
        )
        + r"\par"
    )
    tex.append(r"\begin{itemize}")
    if gaps:
        for g in gaps:
            tex.append(r"\item " + _escape(g))
    else:
        tex.append(r"\item " + _escape("No explicit gaps were extracted; this section is a placeholder."))
    tex.append(r"\end{itemize}")
    tex.append("")

    # ------------------------------------------------------------------
    # PROPOSED EXPERIMENT
    # ------------------------------------------------------------------
    tex.append(r"\section{PROPOSED EXPERIMENT}")
    tex.append(r"\subsection{Hypothesis}")
    hypothesis = experiment_plan.get(
        "hypothesis",
        "A hybrid TPS material configuration improves thermal performance compared to baselines.",
    )
    tex.append(_escape(hypothesis) + r"\par")
    tex.append("")

    tex.append(r"\subsection{Datasets}")
    tex.append(r"\begin{itemize}")
    for d in experiment_plan.get("datasets", []):
        name = _escape(d.get("name", "Dataset"))
        desc = _escape(d.get("description", ""))
        line = r"\item \textbf{" + name + r"}: " + desc
        link = d.get("link")
        if link:
            line += r" (Link: \url{" + link + r"})"
        tex.append(line)
    if not experiment_plan.get("datasets"):
        tex.append(r"\item " + _escape("No datasets specified."))
    tex.append(r"\end{itemize}")
    tex.append("")

    tex.append(r"\subsection{Evaluation Metrics}")
    tex.append(r"\begin{itemize}")
    for m in experiment_plan.get("evaluation_metrics", []):
        metric_name = _escape(m.get("name", ""))
        interpretation = _escape(m.get("interpretation", ""))
        tex.append(r"\item \textbf{" + metric_name + r"} -- " + interpretation)
    if not experiment_plan.get("evaluation_metrics"):
        tex.append(r"\item " + _escape("No metrics specified."))
    tex.append(r"\end{itemize}")
    tex.append("")

    tex.append(r"\subsection{Baseline Methods}")
    tex.append(r"\begin{itemize}")
    for b in experiment_plan.get("baseline_methods", []):
        bname = _escape(b.get("name", ""))
        reason = _escape(b.get("reason", ""))
        tex.append(r"\item \textbf{" + bname + r"} -- " + reason)
    if not experiment_plan.get("baseline_methods"):
        tex.append(r"\item " + _escape("No baseline methods specified."))
    tex.append(r"\end{itemize}")
    tex.append("")

    # ------------------------------------------------------------------
    # METHODOLOGY
    # ------------------------------------------------------------------
    tex.append(r"\section{METHODOLOGY}")
    impl = experiment_plan.get("implementation_notes", {})
    env_desc = impl.get("env", "Simulation environment not fully specified.")
    seed = impl.get("seed", "N/A")
    tex.append(
        _escape(
            f"The proposed experiment is implemented in the following environment: {env_desc}. "
            f"A fixed random seed ({seed}) is suggested for reproducibility."
        )
        + r"\par"
    )
    tex.append("")

    # Equation placeholder
    tex.append(r"\subsection{Governing Equations}")
    tex.append(
        _escape(
            "A simplified one-dimensional heat conduction equation through the TPS stack can be written as:"
        )
        + r"\par"
    )
    tex.append(r"\begin{equation}")
    tex.append(r"\rho c_p \frac{\partial T}{\partial t} = k \frac{\partial^2 T}{\partial x^2} + \dot{q}")
    tex.append(r"\end{equation}")
    tex.append("")

    # Algorithm placeholder (still using algorithm2e)
    tex.append(r"\subsection{Simulation Algorithm}")
    tex.append(
        _escape(
            "Algorithm~\\ref{algo:tps-sim} shows a high-level pseudo-code of the TPS simulation loop."
        )
        + r"\par"
    )
    tex.append(r"\begin{algorithm}[H]")
    tex.append(r"\DontPrintSemicolon")
    tex.append(r"\SetKwProg{Fn}{Function}{ is}{end}")
    tex.append(r"\Fn{simulate\_TPS(material\_stack, heat\_flux\_profile)}{")
    tex.append(r"  initialize\_fields() \;")
    tex.append(r"  \ForEach{time step $t$}{")
    tex.append(r"    apply\_boundary\_conditions(t) \;")
    tex.append(r"    solve\_heat\_equation() \;")
    tex.append(r"    update\_ablation\_and\_stress() \;")
    tex.append(r"  }")
    tex.append(r"}")
    tex.append(r"\caption{High-level TPS simulation loop}")
    tex.append(r"\label{algo:tps-sim}")
    tex.append(r"\end{algorithm}")
    tex.append("")

    # Figure placeholder
    tex.append(r"\subsection{Figures and Tables}")
    tex.append(
        _escape(
            "Figure~\\ref{fig:stack} illustrates a conceptual hybrid TPS material stack. "
            "In an actual paper, this would be replaced by a proper schematic or CAD rendering."
        )
        + r"\par"
    )
    tex.append(r"\begin{figure}[thpb]")
    tex.append(r"      \centering")
    tex.append(r"      \framebox{\parbox{2.8in}{Placeholder for TPS stack figure.}}")
    tex.append(r"      \caption{Conceptual hybrid TPS material stack.}")
    tex.append(r"      \label{fig:stack}")
    tex.append(r"\end{figure}")
    tex.append("")

    # ------------------------------------------------------------------
    # CONCLUSION
    # ------------------------------------------------------------------
    tex.append(r"\section{CONCLUSIONS}")
    conc_text = (
        "This automatically generated paper demonstrates how an AI-based multi-agent system can assist "
        "in structuring a research problem on crew module Thermal Protection Systems. Human researchers "
        "should refine the assumptions, validate the experimental design, and integrate high-fidelity "
        "simulation and test data before any mission-critical deployment."
    )
    tex.append(_escape(conc_text) + r"\par")
    tex.append("")

    # ------------------------------------------------------------------
    # APPENDIX
    # ------------------------------------------------------------------
    tex.append(r"\section*{APPENDIX}")
    tex.append(
        _escape(
            "The appendix can include extended experimental settings, additional plots, or numerical tables. "
            "In the current AI-generated draft, this section acts as a placeholder."
        )
        + r"\par"
    )
    tex.append("")

    # ------------------------------------------------------------------
    # REFERENCES
    # ------------------------------------------------------------------
    tex.append(r"\begin{thebibliography}{99}")
    if citations:
        for i, c in enumerate(citations, start=1):
            authors = _escape(", ".join(c.get("authors", []))) or "Unknown Authors"
            title = _escape(c.get("title", "Untitled"))
            year = _escape(str(c.get("year", "n.d.")))
            venue = _escape(c.get("journal", c.get("venue", "")))
            doi = _escape(c.get("doi", "")) if c.get("doi") else ""
            line = rf"\bibitem{{c{i}}} {authors}, ``{title},'' {venue}, {year}."
            if doi:
                line += f" DOI: {doi}."
            tex.append(line)
    else:
        tex.append(
            r"\bibitem{dummy} References will be populated once structured citation metadata is available."
        )
    tex.append(r"\end{thebibliography}")

    tex.append(r"\end{document}")

    return "\n".join(tex)
